{
  # or for weighted datasets:
  "train-data-paths": [
    'data/slim_pajama/tokenized_train_0-100B/ArXiv/ArXiv',
    'data/slim_pajama/tokenized_train_0-100B/Book/Book',
    'data/slim_pajama/tokenized_train_0-100B/C4/C4',
    'data/slim_pajama/tokenized_train_0-100B/Wikipedia/Wikipedia',
    'data/slim_pajama/tokenized_train_0-100B/Github/Github',
    'data/slim_pajama/tokenized_train_0-100B/StackExchange/StackExchange',
    'data/slim_pajama/tokenized_train_0-100B/CommonCrawl/CommonCrawl',
    'data/pile_replay_shards/replay_10B_2/splits',
    'data/sp_replay_shards/replay_100B_1_shard1/splits',],
  "train-data-weights": [4.03666599074094,
      3.927523855378127,
      25.467175464208918,
      3.7984379710376293,
      4.990226864678155,
      3.1957646326079723,
      49.58420522134826,
      3.8125,
      1.1875],
  "train-iters": 44229,
  "lr-decay-iters": 44229,
  "train-dataset-name": 'slim_pajama_100B_2_replay5',
}