{
"optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.00012,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 0.000012,
  "lr-decay-style": "cosine",
  "warmup": 0.01,
}